version: '3'

services:
    localstack:
        image: localstack/localstack:latest
        ports:
            - "4576:4576"
        environment:
            - SERVICES=sqs
    init:
        build: .
        entrypoint:
            - python3.7
            - create.py
            - A
            - B
        links:
          - localstack
    worker-a:
        build: .
        entrypoint:
            - python3.7
            - increment.py
            - A
            - B
        links:
          - localstack
    worker-b:
        build: .
        entrypoint:
            - python3.7
            - increment.py
            - B
            - A
        links:
          - localstack

